---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-db-cred
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgAwgWTZAErmXosVbWZ+66rewEsX3wbZc0fJ+DOJbqcQmco6rhPHsrnFLoabcFRF/Cp9nDe+dufGiQ+n/WvMvUAkHpMtwU7GXgFV8D3c49ueFQeCLkIIhsja4KSEwTemRyVWFsNdlyM730k3Tv5rcI3QKyFdXNbWtmtY8SbfzIJh4qrkqAN53E5IzEPQS8PzFWvnietxrukFXEw0HjYrRZPmQdpOeCntKoZ511zE9I/cVgcGFsIaU1D5DiUeXpEmSXRpHJMjBPvvuc6DW0+S4Ujd0KgK3DNtVAhRVQG2MaTX8Lr5qxMh2R0sIui7RgYmubE3GHvQkjDh+TNr8t9PlvVdTOt7sKWfD4u2Xmkp+Z27e/YkMVLxLbmL+J+hhFaboL0C9+lOMlNWVv7RsbbnUDyxd2pRIzX/URThFgRF9MTFTy3AQW0Fkq+7huZzzwa4O619MPwKOtyWteNsrvXiw/3jPlxPnyuOgzs+eElpjpl6beO6/JbS42JgO/uut+MQp/nOOh76kt2L7qMoqUIH7KNJW0+MqITSJnjm1DkChAxHkHnPDiDBxh8de/FXwxH+4SPhJNCBRY2fsX47MUabvDM5fTRrw3PnnzOpI1G668rPTAjY6QYiJLHecPeeJwYuUWWqfQt5/ng2srVze7FJ8QQ6B4ZTgFC7GUhKS721djk/kjDfzrbcxAwu2kFT2GUD/rwP6/rW+6GvXvRK4xcDNa4=
    DB_USER: AgARBn5sUMjJut1P/XuzcOQjHldld4dFskY+ReKZ95fdyfUJtd3skPBdbbxwbbVdxfdNu5zhJ9pGl+HAaVIZnb3DUSSwWSDGCBkNniIFQIBEa+kj0JIQGWR3jsJj42L51yfgV1ifFShySnkfhMbKGNiC3/WuE2HQGb9wak3tVD8LIJiwMhLufBGMYOa7HZ18Krj9Qtzr0hlxAso3QriEiR4MbFuJlSXyRDR5+14Mdw0fPZ+YgCwBNQ73XUGu/WoHjYmpJTZLMyS/ATMdsrNlPfjSjAmNc6z0m6wDwmDs9VumeLFhjWpUmD2c+Rt75Z8HY0YumOhqLK6kX6JcQKMQqBPagWt/JOAFBxAGZ+90zNDSLOkxxgt3ihoKfF0BzSD/EfliGXPA2gbcHuw7HdkRQIUaowbsbm5vSKjn0Rsv3HGM87sSUgYXHaL37ZV7nfVujeMLTpIOkuey+R3bFfc9hvdJqevmni6QYhsLkGtAvVC8OppfI5uJnvRC5edzqtYMFlL4mWLLz+VTPoZ9zq+DP17s1c7kPT3eUHj4qTXndDqmggDAG8Oa8wDlFP8mRNR7wEGXd8/rB8cdaZl8Wwqw6r0uipz/U3Omrkce3q5jcKlDxd0zPloNOGyGjlaWsfD7PtTV2ITHstRkjkxCibInz5F90cM//nm3FBtqdTaQTB1emBn2FdVdDJuJIk5oxEIcAo0Jp24LgGdW
  template:
    metadata:
      name: demo-db-cred
      namespace: default
